#!/usr/bin/env perl

use v5.10;
use strict;
use warnings;
use feature 'postderef';
no warnings 'experimental::postderef';

use CfnModel;

my @region_list = qw/
  ap-northeast-1  ap-south-1      ap-southeast-2  eu-central-1  eu-west-2  us-east-2  us-west-2
  ap-northeast-2  ap-southeast-1  ca-central-1    eu-west-1     sa-east-1  us-east-1  us-west-1/;

my $wanted_region = $ARGV[0] or die "Usage: $0 region";

my $regions = {
  map { ($_ => CfnModel->new(file => "spec/$_.json")) } @region_list
};

my $services = { };
foreach my $region (@region_list) {
  foreach my $service ($regions->{ $region }->classes_in_spec->@*) {
    $services->{ $service }->{ $region } = 1;
  }
}

my $error = 0;
foreach my $service (keys $services->%*){
  if (not defined $services->{ $service }->{ $wanted_region }) {
    say "Region $wanted_region doesn't have service $service";
    $error = 1;
  }
}

exit 1 if ($error);
exit 0;

