#!perl

use strict;
use warnings;
use v5.10;
use Module::Find;

my $pattern = $ARGV[0];

my @list = Module::Find::findallmod Cfn::Resource;
@list = map { $_ =~ s/^Cfn::Resource:://; $_ } @list;

if (defined $pattern) {
  @list = grep { $_ =~ m/$pattern/ } @list;
}

say "Supported resources:\n";
say $_ for @list;

exit 0;
